#!/usr/bin/env python3
"""Replace Docent displays with prefill labels, preserving source artifacts.

The durable ledger stores SDK-generated IDs before network writes. An uncertain
upload is checked by those IDs on resume and is never blindly resubmitted.
"""
from __future__ import annotations

import argparse
import copy
import json
import os
from pathlib import Path
import re
import sys
from concurrent.futures import ThreadPoolExecutor
from uuid import uuid4

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from docent.data_models.agent_run import AgentRun
from docent.data_models.transcript import Transcript
from ai_collusion.docent_cli import ensure_public, make_client
from ai_collusion.docent_prefill import prefill_metadata, render_prefill_message
from ai_collusion.runner import load_repo_env


def save(path: Path, value: object) -> None:
    text = json.dumps(value, ensure_ascii=False, indent=2)
    if re.search(r"sk-(?:proj-|ant-)?[A-Za-z0-9_-]{24,}", text):
        raise ValueError("Potential credential in artifact; refusing to write or upload")
    path.parent.mkdir(parents=True, exist_ok=True)
    pending = path.with_name(path.name + ".pending")
    with pending.open("w") as stream:
        stream.write(text + "\n")
        stream.flush()
        os.fsync(stream.fileno())
    os.replace(pending, path)


def strings(value):
    if isinstance(value, str):
        yield value
    elif isinstance(value, list):
        for item in value:
            yield from strings(item)
    elif isinstance(value, dict):
        for item in value.values():
            yield from strings(item)


def copied_run(source: AgentRun, source_collection: str) -> AgentRun:
    if source.transcript_groups or any(t.transcript_group_id for t in source.transcripts):
        raise ValueError("Transcript groups require explicit remapping; unsupported")
    transcripts = [Transcript(
        name=t.name, description=t.description, metadata=copy.deepcopy(t.metadata),
        messages=[render_prefill_message(m) if (m.metadata or {}).get("prefill") is True
                  else m.model_copy(deep=True) for m in t.messages],
    ) for t in source.transcripts]
    mapping = {old.id: new.id for old, new in zip(source.transcripts, transcripts)}
    metadata = copy.deepcopy(source.metadata)
    for annotation in metadata.get("collaboration_judgments", {}).values():
        for event in annotation["judgment"]["evidence"]:
            for quote in event["quotes"]:
                old_id, index = quote["transcript_id"], quote["message_index"]
                message = source.transcript_dict[old_id].messages[index]
                if (message.metadata or {}).get("prefill") is True:
                    raise ValueError("Classifier evidence incorrectly cites prefill")
                if not any(quote["quote"] in s for s in strings(message.model_dump(mode="json"))):
                    raise ValueError("Classifier evidence quote does not match source message")
                quote["transcript_id"] = mapping[old_id]
    metadata.update(source_docent_collection_id=source_collection,
                    source_docent_agent_run_id=source.id,
                    docent_presentation="prefill-prefix-v1")
    result = AgentRun(name=source.name, description=source.description,
                      transcripts=transcripts, metadata=metadata)
    result.metadata.update(prefill_metadata(result))
    return result


def verify(actual: AgentRun, expected: AgentRun) -> None:
    if actual.id != expected.id or actual.metadata != expected.metadata:
        raise ValueError("Run identity or metadata differs from prepared copy")
    if len(actual.transcripts) != len(expected.transcripts):
        raise ValueError("Transcript count differs")
    for got, wanted in zip(actual.transcripts, expected.transcripts):
        if got.id != wanted.id or got.metadata != wanted.metadata:
            raise ValueError("Transcript identity or metadata differs")
        if [m.model_dump(mode="json") for m in got.messages] != [
                m.model_dump(mode="json") for m in wanted.messages]:
            raise ValueError("Message readback differs from exact prepared rendering")


def restore(payload: dict) -> AgentRun:
    # These IDs were generated by SDK constructors and recorded before upload.
    # Preserve them when restoring our own prepared payload after interruption.
    run = AgentRun.model_validate(payload)
    run.model_fields_set.discard("id")
    for transcript in run.transcripts:
        transcript.model_fields_set.discard("id")
    return run


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", required=True)
    parser.add_argument("--name", required=True)
    parser.add_argument("--artifacts", type=Path, required=True)
    parser.add_argument("--expected-count", type=int)
    parser.add_argument("--smoke-only", action="store_true")
    parser.add_argument("--replace-in-place", action="store_true",
                        help="Remove backed-up originals only after replacements verify")
    parser.add_argument("--prefill-only", action="store_true")
    parser.add_argument("--defer-delete", action="store_true",
                        help="Upload and verify all copies, retaining originals for review")
    args = parser.parse_args()
    load_repo_env()
    load_repo_env(Path(__file__).resolve().parents[2] / "debate/.env")
    client = make_client()
    root = args.artifacts
    ledger_path = root / "ledger.json"
    if ledger_path.exists():
        ledger = json.loads(ledger_path.read_text())
        if ledger["source_collection_id"] != args.source or ledger["name"] != args.name:
            raise ValueError("Ledger belongs to a different copy")
        if ledger.get("replace_in_place") != args.replace_in_place:
            raise ValueError("Replacement mode differs from recorded ledger")
    else:
        query = client.execute_dql(args.source,
            "SELECT agent_runs.id AS agent_run_id FROM agent_runs", ensure_latest_results=True)
        if query.get("truncated"):
            raise ValueError("Source listing was truncated")
        ids = sorted(row[0] for row in query["rows"])
        if args.expected_count is not None and len(ids) != args.expected_count:
            raise ValueError(f"Expected {args.expected_count} source runs; found {len(ids)}")
        save(root / "source-listing.json", query)

        def fetch(run_id):
            source = client.get_agent_run(args.source, run_id)
            if source is None:
                raise ValueError(f"Missing source: {run_id}")
            if source.metadata.get("docent_presentation") == "prefill-prefix-v1":
                raise ValueError("Collection already contains copied displays; resume its existing ledger")
            tags = client.get_tags_for_agent_run(args.source, run_id)
            return source, tags

        with ThreadPoolExecutor(max_workers=6) as pool:
            sources = list(pool.map(fetch, ids))
        # Smoke a judged working run first, so citation remapping is exercised.
        sources.sort(key=lambda item: not bool(item[0].metadata.get("collaboration_judgments")))
        if args.prefill_only:
            sources = [(source, tags) for source, tags in sources if any(
                (m.metadata or {}).get("prefill") is True
                for t in source.transcripts for m in t.messages)]
        entries = []
        for source, tags in sources:
            copy_run = copied_run(source, args.source)
            save(root / "source" / f"{source.id}.json", source.model_dump(mode="json"))
            save(root / "prepared" / f"{copy_run.id}.json", copy_run.model_dump(mode="json"))
            entries.append({"source_id": source.id, "destination_id": copy_run.id,
                "transcript_ids": {a.id: b.id for a, b in zip(source.transcripts, copy_run.transcripts)},
                "tags": sorted({t["value"] for t in tags} |
                               set(copy_run.metadata["prefill_annotation"]["tags"])),
                "status": "prepared"})
        ledger = {"source_collection_id": args.source,
                  "destination_collection_id": args.source if args.replace_in_place else str(uuid4()),
                  "name": args.name, "collection_status": "created" if args.replace_in_place else "prepared",
                  "replace_in_place": args.replace_in_place, "original_collection_ids": ids, "runs": entries}
        save(ledger_path, ledger)
    cid = ledger["destination_collection_id"]
    if ledger["collection_status"] != "created":
        if ledger["collection_status"] == "sending":
            raise ValueError("Collection creation outcome uncertain; inspect recorded collection ID")
        ledger["collection_status"] = "sending"
        save(ledger_path, ledger)
        client.create_collection(collection_id=cid, name=args.name,
            description="Display copy of existing runs. Supplied history starts with [PREFILL]. "
                        "Live outputs and classifier evidence are unchanged. Original runs are preserved.",
            metadata={"source_docent_collection_id": args.source,
                      "docent_presentation": "prefill-prefix-v1"})
        ledger["collection_status"] = "created"
        save(ledger_path, ledger)
    ensure_public(client, cid)

    def get_expected(row):
        return restore(json.loads((root / "prepared" / f"{row['destination_id']}.json").read_text()))

    def verify_and_tag(row):
        expected = get_expected(row)
        actual = client.get_agent_run(cid, expected.id)
        if actual is None:
            raise ValueError(f"Recorded upload not readable yet: {expected.id}; do not reupload")
        verify(actual, expected)
        existing = {tag["value"] for tag in client.get_tags_for_agent_run(cid, expected.id)}
        for tag in row["tags"]:
            if tag not in existing:
                client.tag_transcript(cid, expected.id, tag)
        actual_tags = {tag["value"] for tag in client.get_tags_for_agent_run(cid, expected.id)}
        if not set(row["tags"]).issubset(actual_tags):
            raise ValueError("Tag readback mismatch")
        row["status"] = "verified"
        save(ledger_path, ledger)

    rows = ledger["runs"][:1] if args.smoke_only else ledger["runs"]
    for row in rows:
        if row["status"] != "prepared":
            verify_and_tag(row)
    pending = [row for row in rows if row["status"] == "prepared"]
    batches = [pending[:1]] + [pending[i:i+20] for i in range(1, len(pending), 20)]
    for batch in batches:
        if not batch:
            continue
        for row in batch:
            row["status"] = "sending"
        save(ledger_path, ledger)
        response = client.add_agent_runs(cid, [get_expected(row) for row in batch])
        for row in batch:
            row["status"] = "uploaded"
        save(ledger_path, ledger)
        save(root / f"upload-{batch[0]['destination_id']}.json", response)
        for row in batch:
            verify_and_tag(row)
        print(json.dumps({"collection_id": cid, "verified": sum(
            row["status"] == "verified" for row in ledger["runs"])}), flush=True)
    save(root / "validation.json", {"collection_id": cid, "source_count": len(ledger["runs"]),
         "verified_count": sum(row["status"] == "verified" for row in ledger["runs"]),
         "originals_modified": False, "source_backups": "source/", "mapping": "ledger.json"})
    if args.replace_in_place and not args.smoke_only and not args.defer_delete:
        if not ledger.get("replace_in_place"):
            raise ValueError("Ledger was not prepared for replacement")
        if any(row["status"] != "verified" for row in ledger["runs"]):
            raise ValueError("All replacements must verify before originals are removed")
        query = client.execute_dql(cid,
            "SELECT agent_runs.id AS agent_run_id FROM agent_runs", ensure_latest_results=True)
        if query.get("truncated"):
            raise ValueError("Pre-deletion listing was truncated; no deletion performed")
        current = {row[0] for row in query["rows"]}
        originals = {row["source_id"] for row in ledger["runs"]}
        replacements = {row["destination_id"] for row in ledger["runs"]}
        if not replacements.issubset(current):
            raise ValueError("Fresh listing is missing a replacement; no deletion performed")
        to_delete = sorted(originals & current)
        ledger["deletion_planned"] = to_delete
        save(ledger_path, ledger)
        if to_delete:
            count = client.delete_agent_runs(cid, to_delete)
            if count != len(to_delete):
                raise ValueError("Deletion count differs; inspect recorded original IDs")
        final = client.execute_dql(cid,
            "SELECT agent_runs.id AS agent_run_id FROM agent_runs", ensure_latest_results=True)
        if final.get("truncated"):
            raise ValueError("Final collection listing was truncated")
        final_ids = {row[0] for row in final["rows"]}
        expected_ids = (set(ledger["original_collection_ids"]) - originals) | replacements
        if final_ids != expected_ids:
            raise ValueError("Final fresh collection listing differs from expected replacement IDs")
        ledger["deletion_verified"] = True
        save(ledger_path, ledger)
        save(root / "final-listing.json", final)
        save(root / "validation.json", {"collection_id": cid, "verified_count": len(replacements),
             "collection_count": len(final_ids), "original_ids_absent": True,
             "source_artifacts_preserved": True, "source_backups": "source/", "mapping": "ledger.json"})
        print(json.dumps({"collection_id": cid, "replaced": len(replacements),
                          "collection_count": len(final_ids)}), flush=True)


if __name__ == "__main__":
    main()
